//
// AddTimestampRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AddTimestampRequest: Codable, Hashable {

    public var contentHash: String
    public var _prefix: String?

    public init(contentHash: String, _prefix: String? = nil) {
        self.contentHash = contentHash
        self._prefix = _prefix
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contentHash = "content_hash"
        case _prefix = "prefix"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(contentHash, forKey: .contentHash)
        try container.encodeIfPresent(_prefix, forKey: ._prefix)
    }
}

