//
// IssueTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IssueTokenRequest: Codable, Hashable {

    public var amount: Int
    public var tokenType: Int?

    public init(amount: Int, tokenType: Int? = nil) {
        self.amount = amount
        self.tokenType = tokenType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case tokenType = "token_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(tokenType, forKey: .tokenType)
    }
}

