//
// PaymentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentResponse: Codable, Hashable {

    public var txid: String?

    public init(txid: String? = nil) {
        self.txid = txid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case txid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(txid, forKey: .txid)
    }
}

