//
// PaymentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentRequest: Codable, Hashable {

    public var address: String
    public var amount: Int
    public var fee: Int?

    public init(address: String, amount: Int, fee: Int? = nil) {
        self.address = address
        self.amount = amount
        self.fee = fee
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case amount
        case fee
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(fee, forKey: .fee)
    }
}

