//
// TokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TokenResponse: Codable, Hashable {

    public var tokenId: String?
    public var txid: String?

    public init(tokenId: String? = nil, txid: String? = nil) {
        self.tokenId = tokenId
        self.txid = txid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenId = "token_id"
        case txid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tokenId, forKey: .tokenId)
        try container.encodeIfPresent(txid, forKey: .txid)
    }
}

