//
// TokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TokenResponse: Codable, Hashable {

    public var tokensId: String?
    public var txid: String?

    public init(tokensId: String? = nil, txid: String? = nil) {
        self.tokensId = tokensId
        self.txid = txid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokensId = "tokens_id"
        case txid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tokensId, forKey: .tokensId)
        try container.encodeIfPresent(txid, forKey: .txid)
    }
}

