//
// TransferTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransferTokenRequest: Codable, Hashable {

    public var address: String
    public var amount: Int?

    public init(address: String, amount: Int? = nil) {
        self.address = address
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encodeIfPresent(amount, forKey: .amount)
    }
}

