//
// UserinfoResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserinfoResponse: Codable, Hashable {

    public var sub: Int?
    public var balances: UserinfoResponseBalances?
    public var addresses: [String]?

    public init(sub: Int? = nil, balances: UserinfoResponseBalances? = nil, addresses: [String]? = nil) {
        self.sub = sub
        self.balances = balances
        self.addresses = addresses
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sub
        case balances
        case addresses
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sub, forKey: .sub)
        try container.encodeIfPresent(balances, forKey: .balances)
        try container.encodeIfPresent(addresses, forKey: .addresses)
    }
}

