//
// UserinfoResponseBalances.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserinfoResponseBalances: Codable, Hashable {

    public var tpc: Int?

    public init(tpc: Int? = nil) {
        self.tpc = tpc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tpc
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tpc, forKey: .tpc)
    }
}

